analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2370393818709999
  brandStrength: 0.6971326
  lightness: 0.3742725800257176
  brandColors:
    - '#0A0907'
    - '#FE2E4E'
    - '#6E9C30'
    - '#3C611C'
    - '#B4D0A6'
  rhythmicContrast: 0.7544037641491741
typography_spectrum: 0.2580645
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: kg
